name: test

on:
  push:
  pull_request:

jobs:
  test-matrix:
    strategy:
      matrix:
        operating-system:
          [
            ubuntu-latest,
            ubuntu-18.04,
            windows-latest,
            macos-latest,
          ]

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Disable EOL conversions
        run: git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"

      - name: Run unit tests
        run: go test -v ./... -coverprofile=coverage_unit.txt

      - name: Send unit tests coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage_unit.txt
          flags: unit
